name: kalo_landing
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^6.0.0
  simple_rich_text: ^2.0.49
  video_player: ^2.7.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/videos/
    - assets/translations/
    - assets/svg/
